version: '3'

services:
  aws-sqs:
    image: aws-sqs:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - R2DBC_URL=r2dbc:pool:postgres://host.docker.internal:5432/postgres
      - R2DBC_USER=postgres
      - R2DBC_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - AWS_ACCESS_KEY=[PUT_YOUR_ACCESS_KEY]
      - AWS_SECRET_KEY=[PUT_YOUR_SECRET_KEY]
      - AWS_REGION=af-south-1
      - SQS_QUEUE_NAME=sqs.fifo
      - SQS_QUEUE_REGION=af-south-1
    deploy:
      mode: replicated
      replicas: 2